-- Autor: wilmar.castano
-- Creacion del modelo Poliza
-- 2018/09/24

-- CREATE SCHEMA `poliza` DEFAULT CHARACTER SET utf8 ;

DROP TABLE IF EXISTS TPOL_VEHICULO;
DROP TABLE IF EXISTS TPOL_POLIZA;
DROP TABLE IF EXISTS TPOL_ASEGURADO;

CREATE TABLE TPOL_VEHICULO
(
	DS_PLACA VARCHAR(10) NOT NULL COMMENT 'PLACA DEL VEHICULO',
	NM_MODELO INTEGER NOT NULL COMMENT 'MODELO (AÑO) DEL REGISTRO DEL VEHICULO',
	DS_MARCA VARCHAR(30) NOT NULL COMMENT 'MARCA DEL VEHICULO',
	NM_CANTIDAD INTEGER NOT NULL COMMENT 'CANTIDAD MAXIMA DE PASAJEROS QUE PERMITE EL VEHICULO',
	PRIMARY KEY (DS_PLACA)
)  COMMENT='TABLA DONDE SE ALMACENAN LOS DATOS BASICOS DEL VEHICULO';

CREATE TABLE TPOL_POLIZA
(
	DS_NUMERO VARCHAR(100) NOT NULL COMMENT 'NUMERO DE IDENTIFICACION DE LA POLIZA',
	NM_VALOR NUMERIC(14,2) NOT NULL COMMENT 'VALOR DE LA POLIZA ADQUIRIDA POR EL ASEGURADO',
	PRIMARY KEY (DS_NUMERO)
)  COMMENT='TABLA DONDE SE REGISTRA LA INFORMACIÒN DE LA POLIZA';

CREATE TABLE TPOL_ASEGURADO
(
	DS_DOCUMENTO VARCHAR(15) NOT NULL COMMENT 'NUMERO DE IDENTIFICACION DEL ASEGURADO',
	FE_NACIMIENTO DATE NOT NULL COMMENT 'FECHA DE NACIMIENTO DEL ASEGURADO',
	NM_SALARIO NUMERIC(14,2) NOT NULL COMMENT 'SALARIO ACTUAL DEL ASEGURADO',
	NM_CREDITOS NUMERIC(14,2) NOT NULL COMMENT 'VALOR TOTAL DE LOS CREDITOS QUE ACTUALMENTE TIENE EL ASEGURADO',
	NM_GASTOS_FIJOS NUMERIC(14,2) NOT NULL COMMENT 'VALOR TOTAL DE LOS GASTOS FIJOS QUE TIENE EL ASEGURADO',
	PRIMARY KEY (DS_DOCUMENTO)
)  COMMENT='TABLA DONDE SE REGISTRA LA INFORMACIÒN DEL ASEGURADO';

CREATE TABLE TPOL_AFILIACION
(
	NM_ID INTEGER NOT NULL AUTO_INCREMENT COMMENT 'IDENTIFICADOR DE LA AFILIACION',
	DS_DOCUMENTO_ASEGURADO VARCHAR(15) NOT NULL COMMENT 'NUMERO DE IDENTIFICACION DEL ASEGURADO',
	DS_NUMERO_POLIZA VARCHAR(100) NOT NULL COMMENT 'NUMERO DE IDENTIFICACION DE LA POLIZA',
	DS_PLACA_VEHICULO VARCHAR(10) NOT NULL COMMENT 'PLACA DEL VEHICULO',
	PRIMARY KEY (NM_ID)
)  	COMMENT='TABLA DONDE SE REGISTRA LA INFORMACIÒN DEL ASEGURADO';

ALTER TABLE TPOL_AFILIACION ADD CONSTRAINT FK_TPOL_AFILIACION_TPOL_ASEGURADO 
	FOREIGN KEY (DS_DOCUMENTO_ASEGURADO) REFERENCES TPOL_ASEGURADO (DS_DOCUMENTO)
;

ALTER TABLE TPOL_AFILIACION ADD CONSTRAINT FK_TPOL_AFILIACION_TPOL_POLIZA 
	FOREIGN KEY (DS_NUMERO_POLIZA) REFERENCES TPOL_POLIZA (DS_NUMERO)
;

ALTER TABLE TPOL_AFILIACION ADD CONSTRAINT FK_TPOL_AFILIACION_TPOL_VEHICULO
	FOREIGN KEY (DS_PLACA_VEHICULO) REFERENCES TPOL_VEHICULO (DS_PLACA)
;
